on:
  workflow_run:
    workflows: [Rust]
    types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-latest
    steps:
    - if: ${{ github.event.workflow_run.conclusion == 'success' }}
      run: echo 'The triggering workflow succeeded'
    - if: ${{ github.event.workflow_run.conclusion == 'failure' }}
      run: echo 'The triggering workflow failed'
