# Workflow Commit Status runs after all other checks for a commit or PR. It's
# succeeded job can be used as a single check to reference whether all other
# checks have succeeded and the commit is cleared all build requirements.

name: Commit Status

on:
  status

jobs:
  succeeded:
    runs-on: ubuntu-latest
    if: ${{ github.event.state != 'pending' }}
    steps:
    - run: |
        echo 'Triggered by: ${{ github.event.target_url }}'
        echo 'Description: ${{ github.event.description }}'
        echo 'Branches: ${{ github.event.branches }}'
        echo 'SHA: ${{ github.event.sha }}'
        echo 'State: ${{ github.event.state }}'
    - if: ${{ github.event.state != 'success' }}
      run: exit 1
